feature/SOMS/container UserID field added
KwonSunJae/CloudPlatform pull request #45
Opened 2024-03-14 11:50 UTC by minikryc

container에 UserID 필드 RequestBody에 추가

2024-03-16 16:57 UTC, KwonSunJae requested changes
DB생성할때 CREATE에 UserID Foreign Key로 생성되는 부분은 수정안된 것 같네요

2024-03-18 04:54 UTC, minikryc commented
수정했습니다

2024-03-25 06:46 UTC, KwonSunJae approved these changes

2024-03-25 06:46 UTC, KwonSunJae commented
LGTM

2024-03-25 06:46 UTC, merged